# Generated by Django 3.2.7 on 2021-12-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20211214_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='numero_calle',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
